In [29]:
# Library
# numpy.org
import numpy, time

In [4]:
# If we want to see what's available
#dir(numpy)

In [11]:
x = numpy.zeros(2)
print(x)
# Makes y a reference to x
y = x
x[0]=1; print x,y

[ 0.  0.]
[ 1.  0.] [ 1.  0.]


In [10]:
print x is y

True


In [13]:
z = x.copy()
print z is x

False


In [17]:
# Can fill arrays with values
print numpy.linspace(0,1,6)
print numpy.arange(0,1,0.2)

[ 0.   0.2  0.4  0.6  0.8  1. ]
[ 0.   0.2  0.4  0.6  0.8]


In [18]:
# Arrays from lists
la = [1.,2.,3.]
a = numpy.array(la)
print a

[ 1.  2.  3.]


In [19]:
# Arrays from lists
lb = [4.,5.,6.]
b = numpy.array(lb)
print b

[ 4.  5.  6.]


In [21]:
# We can combine into larger arrays
ab = numpy.array([la,lb])
print ab

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [22]:
# Normal way of accessing file
for line in open('a.dat'):
    print line

1. 2. 3.

4. 5. 6.


In [28]:
# Load data from a file
a = numpy.loadtxt('a.dat')
print a
# We can easily change the shape of an array
print a.shape
a.shape = (6,)
print a.shape

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
(2, 3)
(6,)


In [32]:
n = 256
a = numpy.ones((n,n))
b = numpy.ones((n,n))
c = numpy.zeros((n,n))
t1 = time.clock()
for i in range(n):
    for j in range(n):
        for k in range(n):
            c[i,j] += a[i,k]*b[k,j]
t2 = time.clock()
print("Loop timing",t2-t1)

('Loop timing', 12.151718999999998)


In [33]:
t1 = time.clock()
c = numpy.dot(a,b)
t2 = time.clock()
print("dot timing",t2-t1)

('dot timing', 0.01580600000000132)
